### ISSUE TITLE
您好，知了的agent已经全面失效。2019 2020全部无效.

### ISSUE THREAD

**Issue by ScSofts** [czl0325/jetbrains-agent-latest#1]
使用java.exe运行可以看到信息，但是并没有作用。
信息如下
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

 ====================================================
 =======        Jetbrains License Crack       =======
 =======           https://zhile.io           =======
 ====================================================

 @See: https://zhile.io/2018/08/17/jetbrains-license-server-crack.html

 @Version: 3.2.1, @Build Date: 2020-04-11

**Comment by Cooboob** [comment]
说失效的，关注大神公众号有惊喜......
